### ISSUE TITLE
Windows build manual for Spectrum2

### ISSUE THREAD

**Issue by 3apa3a-b-ta3e** [SpectrumIM/spectrum2#110]
I can only find the manual for first version. Can I somehow build 2.0.1 for Windows by myself?
OR can someone share win32 binary?

**Comment by vitalyster** [comment]
Maybe it is a bit outdated but in general it should be ok - https://github.com/hanzz/spectrum2/blob/gh-pages/documentation/installation/windows.md

**Comment by 3apa3a-b-ta3e** [comment]
Sounds a little tricky for just one app. I just want to move from Linux to Windows because new releases for Debian is AMD64-only and i don`t have AMD64 Linux VM, only Windows with Openfire.
Maybe someone already compiled this binary?

**Comment by hanzz** [comment]
If you have 32 bit VM, it's probably much easier to compile on 32bit linux than on windows.

**Comment by QomariSanjaya** [comment]
Is there anyone has the windows build? I am a newbie, i cant build if by my self

**Comment by vitalyster** [comment]
Show your build errors

**Comment by QomariSanjaya** [comment]
I even dont understand the first step. That tutorial is too expert language.

**Comment by vitalyster** [comment]
Please ask exact questions and I will fix "language" in the tutorial

**Comment by QomariSanjaya** [comment]
Environment step No. 0. "and add it to %PATH%." What is %PATH% mean?

**Comment by vitalyster** [comment]
it is ![environment variable](https://user-images.githubusercontent.com/1052407/27515593-6584f6a0-59af-11e7-9118-b369ab7f0d4d.PNG)

**Comment by QomariSanjaya** [comment]
Its too complicated for me, is there someone who has the windows build? So i can just install the .exe format?

**Comment by vitalyster** [comment]
Sorry, windows support isn't ready for end user

**Comment by vitalyster** [comment]
You can grab now appveyor artifacts or follow appveyor config to build windows binaries
