### ISSUE TITLE
feature request: add vCard mappings from libpurple/ICQ user's detail

### ISSUE THREAD

**Issue by drook** [SpectrumIM/spectrum2#115]
I'm often seeing lines in logs, similar to the following:

``` log
51415: 2016-02-29 12:00:25,763 WARN  backend: Unhandled VCard Label 'UIN' 247486210
51415: 2016-02-29 12:00:25,763 WARN  backend: Unhandled VCard Label '?????????' Rubincomputers
51415: 2016-02-29 12:00:25,763 WARN  backend: Unhandled VCard Label '??????' ?????
51415: 2016-02-29 12:00:25,763 WARN  backend: Unhandled VCard Label '?????' Perm
```

("???" stands for national encoding, I guess something isn't configured properly on my side, anyway national symbols work fine in a client).

Would be just great if these fields were mapped to the vCard fields. If strict mapping isn't possible would be nice to just map them to the "About" vCard field, which is just some formatted text.

**Comment by vitalyster** [comment]
purple-icq is dead
