### ISSUE TITLE
Feedback when connected to IRC

### ISSUE THREAD

**Issue by jean** [SpectrumIM/spectrum2#121]
I connected an IRC channel to Slack:

| Slack channel | 3rd-party room name | 3rd-party server | Nickname in 3rd-party room | Actions |
| --- | --- | --- | --- | --- |
| irc-testingtesting123 | #testingtesting123 | irc.freenode.net | spectrum2 | Leave |

Now all utterances in the IRC channel is repeated:

> 8:53 PM <•neaj> talking in IRC
> 8:53 PM < spectrum2> < Spectrum 2> talking in IRC
> 8:53 PM < spectrum2> < jean> talking in slack
> 8:53 PM <•neaj> who thought this was a good idea
> 8:53 PM < spectrum2> < Spectrum 2> who thought this was a good idea

This breaks the IRC channel.

How is it supposed to work?

**Comment by hanzz** [comment]
This is definitely bug in our end, I will investigate it more when having some time.
