### ISSUE TITLE
Libpurple backend: Messages to people not in contact list are not delivered until reconnect (wrong internal spectrum2 contact name).

### ISSUE THREAD

**Issue by homocogitum** [SpectrumIM/spectrum2#125]
Some time ago I reported about a bug in libpurple backend related to problems with Telegram transport, when Cyryllic usernames with capital letters were not correctly translated from internal spectrum2 name to libpurple name. That bug was corrected, now I have found another similar one, related to nicknames with capital letters.
In telegram transport, when i have new incoming message from user that I haven't in the contact list, the messages i send to him are not delivered.
The messages are delivered only when i reconnect to transport.
And before the reconnect user in the roster has name like "name\20surname@telegram.myserver".
And after reconnect it changes to "Name Surname" and messages are delivered fine.
Using debug i discovered that before reconnect messages are sent to user with nickname with all small letters, without capital letters, to user "name surname", not "Name Surname".

**Comment by vitalyster** [comment]
Is remote roster feature enabled on server?

**Comment by vishnyakov-aleks** [comment]
No, remote roster was disabled. Problem is actual ex. in telegram, when user, who never was in roster - write to you. you see him messages, but can not write to him. reconnect to server resolves a problem

**Comment by vitalyster** [comment]
Should work correctly with tdlib-purple
