### ISSUE TITLE
Photo attachments receive

### ISSUE THREAD

**Issue by vishnyakov-aleks** [SpectrumIM/spectrum2#161]
How I can receive photo attachments from telegram? 
I am using telegram-purple + spectrum2 + ejabberd
If anyone can help with my problem - contact me (Skype vishnyakov.aleks)

**Comment by vitalyster** [comment]
photos should be shown as links in messages. What did you instead?

**Comment by vishnyakov-aleks** [comment]
I see many spaces :-)
But I used asmack library for android. I 'll try psi+ today

**Comment by vishnyakov-aleks** [comment]
yes, on psi+ i see only whitespaces

```
<!-- TS:2016-08-18T22:19:21--><message from="***************.ru/bot" type="chat" to="7916**********.ru">
<body>
</body>
<html xmlns="http://jabber.org/protocol/xhtml-im">
<body xmlns="http://www.w3.org/1999/xhtml">
<br/>
</body>
</html>
</message>
```

**Comment by vishnyakov-aleks** [comment]
Hi, what about it?

**Comment by vishnyakov-aleks** [comment]
Telegram-purple is supports photo receive. Can you try to fix bug in spectrum plz?

**Comment by vitalyster** [comment]
@vishnyakov-aleks I can not reproduce your issue, I see links in messages

**Comment by vishnyakov-aleks** [comment]
@vitalyster What's your config? What foreground, client?

**Comment by xpectdelays** [comment]
Hello, I have this issue as well, with a Prosody server and Tigase Messenger on the mobile and Thunderbird on the desktop. The images are downloaded fine, they are placed in the configured 'web storage' directory. But the link is not sent.

It appears to me, looking at my logs, which appear to be insanely verbose for some reason (gonna have to fix that), what Spectrum is doing, is putting an IMG tag into the message. This is not supported by too many XMPP clients and the documentation is extremely misleading on this point. Folks expect a clickable hyperlink, I believe, and many XMPP clients strip out many/most tags from the XHTML. Is 'IMG' even allowed by the XHTML XEP? Seems like a bad idea in any case.

If nothing else, please clarify the docs. Preferably, provide an option to use hyperlinks.

**Comment by xpectdelays** [comment]
@vishnyakov-aleks yes, but it looks as though the link is sent in the plain text portion of the XHTML message. But I can tell you that some clients "handle" XHTML-IM by displaying the html part and sanitizing it (whatever that means). So it is possible that the IMG tag just gets obliterated and hence the empty message. It would be better if spectrum provided some plain or hyperlinked text in the XHTML so as to behave as expected with these clients.

Furthermore, while IMG is supported by XHTML-IM, the xep makes clear clients cannot be expected to simply blindly render the image referenced. I don't know too much about the real world behavior of other clients but this issue report suggests some other approach should at least be available.

**Comment by xpectdelays** [comment]
Hi, changing the replaced body to an 'a href' works great. Be interested to know in what configuration the original behavior has been tested and/or is expected to work (Slack?) but it doesn't really matter. Please provide the hyperlink in some manner within the XHTML-IM portion of the message so as to work properly with more XMPP clients.

**Comment by vishnyakov-aleks** [comment]
@xpectdelays i was tried to change this line 
` std::string img = "<img src=\"" + src + "\"/>";
`to 
` std::string img = "<a href=\"" + src + "\"/>"; 
`or to
` std::string img = src; 
`
then i did cmake, make and make install.
but i have no positive result. 
What is wrong in my steps?

**Comment by jihadismail8** [comment]
@xpectdelays  tell us how you made the images work please :)

**Comment by vitalyster** [comment]
Images are received only when web storage is configured - https://spectrum.im/documentation/configuration/web_storage.html
