### ISSUE TITLE
Added telegram purple contacts cannot send out messages

### ISSUE THREAD

**Issue by languitar** [SpectrumIM/spectrum2#175]
I am using spectrum 2 as a transport for an ejabberd server with the telegram purple transport. When manually adding contacts using the transport jids in the format `forename\20lastname@telegram-transport.example.org`, the contacts end up in the `buddies` table with `forename lastname` being the content of the `uin` column. This way, the contact can receive messages, but sending out messages doesn't work. When manually fixing the column to be `Forename Lastname` (mind the capital letters), things start to work.

In the broken case, I can see the following errors in the backend log:
```
16: 2016-12-30 10:43:40,630 INFO  libpurple: prpl-telegram:tgprpl_send_typing()                                                      
16: 2016-12-30 10:43:40,631 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed                                
16: 2016-12-30 10:43:40,673 INFO  backend: Sending message to 'forename lastname'                                                    
16: 2016-12-30 10:43:40,673 INFO  libpurple: prpl-telegram:tgprpl_send_im()                                                   
16: 2016-12-30 10:43:40,673 ERROR backend: g_log tgp_blist_lookup_peer_get: assertion 'id' failed                                   
16: 2016-12-30 10:43:40,673 INFO  libpurple: prpl-telegram:peer not found 
```

I am not sure whether spectrum or telegram-purple are the origin of this issue, but since the `database.sql` seems to be created by spectrum, I filed the issue here first.

I have manually built the dockerfile for spectrum yesterday, so all version of the software are recent.

**Comment by vitalyster** [comment]
1) username part of XMPP JID is case-insensitive, so it doesn't matter for most other protocols where user id is case-insensitive which case is in database
2) As I understand, telegram protocol have some issues to access real user id, see https://github.com/hanzz/spectrum2/issues/86 - so purple-telegram authors choose to use case-sensitive buddy names as user ids.
3) spectrum have some support of mapping case-sensitive name to case-insensitive JID, you should not edit database, just relogin after adding new contact. There is a problem to map contact jid until something will be received from this contact.

**Comment by languitar** [comment]
I know that JIDs are case-insensitive. However, from a user perspective, this is a serious trouble. I tried relogging in a few times and I also constantly received messages from the contact for testing purposes. Nothing of this helped. So is this then a bug that should be reported at telegram purple?

**Comment by languitar** [comment]
Just for the reference, this might be related: https://github.com/hanzz/spectrum2/issues/86

**Comment by heeplr** [comment]
> username part of XMPP JID is case-insensitive, so it doesn't matter for most other protocols where user id is case-insensitive which case is in database

It seems to matter in this case. Since Spectrum is to bind other protocols to XMPP, it shouldn't touch letter casing to support case-sensitive protocols.

> spectrum have some support of mapping case-sensitive name to case-insensitive JID, you should not edit database, just relogin after adding new contact. There is a problem to map contact jid until something will be received from this contact.

This didn't solve it for me. I constantly receive messages with spectrum as I use the same account with Pidgin but sending doesn't work from spectrum. I had to edit the database.sql to make it work.

**Comment by vitalyster** [comment]
This should work correctly with tdlib-purple
