### ISSUE TITLE
outdated purple-skypeweb in Docker image

### ISSUE THREAD

**Issue by t184256** [SpectrumIM/spectrum2#180]
I installed spectrum2 the docker way, gateway mode (oh why did I? it worked great before...). After the registration my Skype gateway started sending me

```
Failed getting PIE value
```

`docker logs` reveals
```
INFO  NetworkPluginServer: Associating <JID> with this backend
INFO  User: <JID> : Disconnected from legacy network with error Failed getting PIE value
```

The discussion at https://github.com/EionRobb/skype4pidgin/issues/506 suggests that upgrading skype4pidgin to [1.2.2](https://github.com/EionRobb/skype4pidgin/releases/tag/1.2.2) fixes the issue.

If this is the fix, could you upgrade the docker image? Thank you.

**Comment by t184256** [comment]
Got tired of waiting, rebuilt it myself, published as [t184256/spectrum2-issue-180](https://cloud.docker.com/app/t184256/repository/docker/t184256/spectrum2-issue-180). Works for me.

**Comment by mbirth** [comment]
Docker image is still at 2.0.2 from a year ago.

**Comment by jihadismail8** [comment]
t184256 , your link is dead , can you please upload it again ?? thanks

**Comment by t184256** [comment]
@jihadismail8 Here's a better link: https://hub.docker.com/r/t184256/spectrum2-issue-180

Nothing fancy by the way, I've just rebuilt it. I think it's better to rebuild it yourself with all the recent modifications. The official Dicker image must be really abandoned, but the repo seems to be more lively.

**Comment by t184256** [comment]
Rebuilt with aaf3ead  and repushed, works for me.

**Comment by vitalyster** [comment]
Spectrum Docker image now lives in spectrum2/spectrum repo
