### ISSUE TITLE
Twitter avatars shouldn’t be considered UTF-8

### ISSUE THREAD

**Issue by linkmauve** [SpectrumIM/spectrum2#208]
When fetching the Twitter avatars using spectrum2_twitter_backend, this error is sent to journald:
```
spectrum2_manager[14986]: [libprotobuf ERROR google/protobuf/wire_format_lite.cc:629] String field 'pbnetwork.Buddy.iconHash' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

It doesn’t seem to cause any issue though, I can see the avatars of both of my followees.

**Comment by vitalyster** [comment]
Swiften version?

**Comment by linkmauve** [comment]
Latest master, c918e324, using the patch rion☫ posted yesterday at [spectrum@conference.spectrum.im](xmpp:spectrum@conference.spectrum.im?join) (http://termbin.com/pho3).

**Comment by linkmauve** [comment]
I just found that in the same logs, I’m not sure if it’s related or not:
```
spectrum2_manager[21182]: spectrum2_twitter_backend: backends/twitter/rapidjson/document.h:424: int64_t rapidjson::GenericValue<Encoding, Allocator>::GetInt64() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; int64_t = long int]: Assertion `flags_ & kInt64Flag' failed.
```

**Comment by Fank** [comment]
relates to #207

**Comment by vitalyster** [comment]
Looks like it was fixed by switching to jsoncpp
