### ISSUE TITLE
Twitter component sends unneeded presence updates when another resource connects

### ISSUE THREAD

**Issue by linkmauve** [SpectrumIM/spectrum2#217]
How to reproduce:
- Connect with client A.
- Open XML console in client A.
- Connect with Gajim.
- See eight incoming presences towards A, while none were expected.

**Comment by linkmauve** [comment]
Actually it’s Gajim’s presence it is broadcasting to A, which includes Gajim’s capabilities.  This behaviour is wrong.

**Comment by vitalyster** [comment]
Discussed in #256
