### ISSUE TITLE
Steam will flood prosody trunk with stanza updates.

### ISSUE THREAD

**Issue by Fank** [SpectrumIM/spectrum2#218]
Didn't happend with prosody 0.9 and 0.10 .

**Comment by Fank** [comment]
maybe related to #217

**Comment by vitalyster** [comment]
Maybe you have only one connected resource with 0.9?

**Comment by Fank** [comment]
i didn't use 0.9 long, only 0.10 and trunk mostly, no mostly i have >= 3 resources connected.

**Comment by Fank** [comment]
I can confirm this happens with multiple libpurple backends not only steam

**Comment by Fank** [comment]
Relates #204    
Did some testing, this only happens if >= 2 ressources are connected, my example desktop (pidgin) and mobile (conversations). And both will connection at the same time if spectrum is online, looks like it happens after the first connection (after steam guard key entered).

**Comment by vitalyster** [comment]
What about prosody 0.9? Maybe need to disable some modules (carbons)?

**Comment by Fank** [comment]
I switched from prosody to mongooseim and spectrum is working fine with multiple ressources -> closed because its related to prosody and not spectrum.
