### ISSUE TITLE
Can't load configuration file

### ISSUE THREAD

**Issue by QomariSanjaya** [SpectrumIM/spectrum2#231]
Using Debian Stretch and installing spectrum 2 by this tutorial: http://spectrum.im/documentation/installation/packages_debian_ubuntu.html

Already create the config file located in /etc/spectrum2/transports
But when trying starting the spectrum i got this

# spectrum2_manager start
Can't load configuration file.

Please any help?

**Comment by vitalyster** [comment]
Looks like you miss manager configuration file (`/etc/spectrum2/spectrum_manager.cfg` by default)
See example here - https://github.com/SpectrumIM/spectrum2/blob/master/spectrum_manager/src/spectrum_manager.cfg

**Comment by QomariSanjaya** [comment]
I see, the file spectrum_manager.cfg need to create manually on this Spectrum version: 2.0.3-2~stretch
