### ISSUE TITLE
Installing Failed

### ISSUE THREAD

**Issue by QomariSanjaya** [SpectrumIM/spectrum2#240]
```
root@chat:~# apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 1AFDEA51
Executing: /tmp/apt-key-gpghome.07y4uonpFj/gpg.1.sh --keyserver hkp://pool.sks-keyservers.net --recv-keys 1AFDEA51
gpg: key E01FC4111AFDEA51: "Vitaly Takmazov <vitalyster@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@chat:~# curl https://swift.im/keys/packages.key | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3172  100  3172    0     0   1353      0  0:00:02  0:00:02 --:--:--  1353
OK
root@chat:~# echo "deb http://packages.spectrum.im/spectrum2/ stretch main" >> /etc/apt/sources.list.d/spectrum.list
root@chat:~# echo "deb https://swift.im/packages/debian/sid beta main" >> /etc/apt/sources.list.d/spectrum.list
root@chat:~# apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ InRelease
Hit:3 http://ftp.debian.org/debian stretch-updates InRelease
Ign:5 http://ftp.debian.org/debian stretch InRelease
Get:4 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Release [982 B]
Hit:6 http://packages.spectrum.im/spectrum2 stretch InRelease
Get:7 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Release.gpg [481 B]
Hit:8 http://ftp.debian.org/debian stretch Release
Err:7 http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Release.gpg
  The following signatures were invalid: EXPKEYSIG 12C6ADA61C85BB5E home:jgeboski OBS Project <home:jgeboski@build.opensuse.org>
Fetched 1,463 B in 1s (952 B/s)
Reading package lists... Done
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0 ./ Release: The following signatures were invalid: EXPKEYSIG 12C6ADA61C85BB5E home:jgeboski OBS Project <home:jgeboski@build.opensuse.org>
E: Failed to fetch https://swift.im/packages/debian/sid/dists/beta/InRelease
W: Failed to fetch http://download.opensuse.org/repositories/home:/jgeboski/Debian_9.0/./Release.gpg  The following signatures were invalid: EXPKEYSIG 12C6ADA61C85BB5E home:jgeboski OBS Project <home:jgeboski@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:1 and /etc/apt/sources.list.d/spectrum.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:2 and /etc/apt/sources.list.d/spectrum.list:4
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:2 and /etc/apt/sources.list.d/spectrum.list:4
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:2 and /etc/apt/sources.list.d/spectrum.list:4
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/spectrum.list:2 and /etc/apt/sources.list.d/spectrum.list:4
root@chat:~# apt-get install spectrum2 spectrum2-backend-libpurple spectrum2-backend-libcommuni spectrum2-backend-twitter
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 spectrum2 : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
             Depends: libswiften4 but it is not installable
 spectrum2-backend-libcommuni : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                                Depends: libswiften4 but it is not installable
 spectrum2-backend-libpurple : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                               Depends: libswiften4 but it is not installable
 spectrum2-backend-twitter : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                             Depends: libswiften4 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by vitalyster** [comment]
> N: Is the package apt-transport-https installed?
install `apt-transport-https` and then `libswiften4` will be available

**Comment by QomariSanjaya** [comment]
Its not helping, still installation failed

root@chat:~# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 171 kB of archives.
After this operation, 242 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian stretch/main amd64 apt-transport-https amd64 1.4.7 [171 kB]
Fetched 171 kB in 2s (58.1 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 78283 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.4.7_amd64.deb ...
Unpacking apt-transport-https (1.4.7) ...
Setting up apt-transport-https (1.4.7) ...
root@chat:~# apt-get install spectrum2 spectrum2-backend-libpurple spectrum2-backend-libcommuni spectrum2-backend-twitter
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 spectrum2 : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
             Depends: libswiften4 but it is not installable
 spectrum2-backend-libcommuni : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                                Depends: libswiften4 but it is not installable
 spectrum2-backend-libpurple : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                               Depends: libswiften4 but it is not installable
 spectrum2-backend-twitter : Depends: libtransport2.0 (= 1:2.0.5-1) but 1:2.0.3-2~stretch-1 is to be installed
                             Depends: libswiften4 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@chat:~# Reading package lists... Done

**Comment by vitalyster** [comment]
apt-get install libswiften4

**Comment by QomariSanjaya** [comment]
I got this

`root@chat:~# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version (1.4.7).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up spectrum2 (1:2.0.5-1) ...
Job for spectrum2.service failed because the control process exited with error code.
See "systemctl status spectrum2.service" and "journalctl -xe" for details.
invoke-rc.d: initscript spectrum2, action "start" failed.
● spectrum2.service - spectrum2
   Loaded: loaded (/lib/systemd/system/spectrum2.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2017-10-02 23:59:15 EDT; 42ms ago
  Process: 1165 ExecStart=/usr/bin/spectrum2_manager start (code=exited, status=4)

Oct 02 23:59:15 chat.fortunecells.com systemd[1]: Starting spectrum2...
Oct 02 23:59:15 chat.fortunecells.com spectrum2_manager[1165]: Can't load configuration file.
Oct 02 23:59:15 chat.fortunecells.com systemd[1]: spectrum2.service: Control process exited, code=exited status=4
Oct 02 23:59:15 chat.fortunecells.com systemd[1]: Failed to start spectrum2.
Oct 02 23:59:15 chat.fortunecells.com systemd[1]: spectrum2.service: Unit entered failed state.
Oct 02 23:59:15 chat.fortunecells.com systemd[1]: spectrum2.service: Failed with result 'exit-code'.
dpkg: error processing package spectrum2 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 spectrum2
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by vitalyster** [comment]
put spectrum2_manager config in the expected place https://github.com/SpectrumIM/spectrum2/blob/master/spectrum_manager/src/spectrum_manager.cfg

**Comment by vitalyster** [comment]
It's the same issue as you asked before - https://github.com/SpectrumIM/spectrum2/issues/231
and you lost this file again
