### ISSUE TITLE
spectrum2_libpurple_backend very much use cpu on vps up to100%

### ISSUE THREAD

**Issue by ArivhaySoft** [SpectrumIM/spectrum2#242]
why is this happening?
after I try check with spectrum2_manager telegram.domain.com status

the effect of this is the slowing down of the telegram response 

then emerge:
Warning: Pending events in SimpleEventLoop at destruction time

please help and what should i do?

**Comment by vitalyster** [comment]
It looks like backend crashed and restarted again, can you please get a core dump?

**Comment by ArivhaySoft** [comment]
how do i take core dump?
Sorry I'm newbie in this case

**Comment by vitalyster** [comment]
http://spectrum.im/documentation/management/getting_backtrace.html

**Comment by vitalyster** [comment]
Considering it is a telegram-purple or tgl issue, feel free to add a backtrace and I will reopen if it is Spectrum-related
