### ISSUE TITLE
Whatsapp backend is not working

### ISSUE THREAD

**Issue by cutec-chris** [SpectrumIM/spectrum2#243]
Iam getting:
2017-10-16 16:49:33,817 INFO  NetworkPluginServer: Tried to spawn first backend with pid 42
2017-10-16 16:49:33,817 INFO  NetworkPluginServer: Backend should now connect to Spectrum2 instance. Spectrum2 won't accept any connection before backend connects
Traceback (most recent call last):
  File "/opt/transwhat/transWhat/transwhat.py", line 40, in <module>
    from Spectrum2.iochannel import IOChannel
ImportError: No module named Spectrum2.iochannel

Anyone who has run this ?

**Comment by vitalyster** [comment]
This module is in transwhat directory, make sure you have it in your PYTHONPATH.
Anyway it is not a spectrum issue itself, but transwhat one

**Comment by cutec-chris** [comment]
Its in the official Docker Image, so is that really an transwhat issue ? Or an issue of the Sectrum2 Docker Image ?

**Comment by vitalyster** [comment]
Third-party plugins in spectrum Docker image are added as is, without proper setup. If you can improve it - let us know, please.

**Comment by vitalyster** [comment]
Also, be warned, WhatsApp may block you phone number while using third-party clients

**Comment by cwildfoerster** [comment]
Why adding plugins if they do not even work without a lot of further work?

**Comment by thundergreen** [comment]
Why people always complain about stuff instead of cresting their own

**Comment by cutec-chris** [comment]
why people always complain about complaining :)

**Comment by thundergreen** [comment]
Why people just don't talk.... ;)
