### ISSUE TITLE
Encoding vCard in ICQ

### ISSUE THREAD

**Issue by sosed213** [SpectrumIM/spectrum2#244]
Run Spectrum2 in the dock with the server ejabberd. All is well, but information about contacts in an incomprehensible coding on different clients.

A similar problem in PyICQt decided to install the encoding
<encoding>cp1251</encoding>

**Comment by vitalyster** [comment]
add `encoding=windows-1251` to `[purple]` section of the icq instance config

**Comment by sosed213** [comment]
thank you very much
