### ISSUE TITLE
Duplicated messages with discord 

### ISSUE THREAD

**Issue by thundergreen** [SpectrumIM/spectrum2#247]
https://emevth.no-ip.biz/share/thorsten/xsY6dKMYiPFYTds7/20171031_204139214_fb38.jpg

As well seen there are duplicated messages .using latest discord and spectrum 2

**Comment by vitalyster** [comment]
Should be fixed in https://github.com/SpectrumIM/spectrum2/commit/401deee43baac1b0102438b414501188e39dd7ff
