### ISSUE TITLE
Twitter mode 1 not working

### ISSUE THREAD

**Issue by thundergreen** [SpectrumIM/spectrum2#249]
after swithcing to mode 1 this happens:

spectrum2_twitter_backend: /home/orangepi/spectrum2-2.0.5/backends/twitter/rapidjson/document.h:333: rapidjson::SizeType rapidjson::GenericValue<Encoding, Allocator>::Size() const [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]: Assertion `IsArray()' failed.

**Comment by vitalyster** [comment]
Fixed in master
