### ISSUE TITLE
[Request] Packaging for fedora

### ISSUE THREAD

**Issue by Postroutine** [SpectrumIM/spectrum2#250]
I see a rpm.spec in /packaging/fedora/spectrum2.spec and the dockerfile use Fedora as image, but spectrum2 is not in Fedora repositories. Is it planned?

**Comment by vitalyster** [comment]
https://copr.fedorainfracloud.org/coprs/mcepl/spectrum2/

**Comment by Postroutine** [comment]
Why this repo provide his own glib?

**Comment by vitalyster** [comment]
I’m only seeing empty directory for glib :)
