### ISSUE TITLE
Getting "Feature not supported" when trying to register with transport

### ISSUE THREAD

**Issue by Knezzen** [SpectrumIM/spectrum2#257]
Having spent most of the evening trying to get Spectrum to play along nicely with Jabberd2 I'v I given up. Spectrum can cummunicate just fine with Jabberd2 and transports gets listed amongst the services. When I try to register, though, the client (Psi is what I'm using) says "Unable to retrieve registration form. Reason: Feature not implemented. The feature requested is not implemented by the recipient or server and therefore cannot be processed.

This is what I'm getting on the server side (from the ICQ transport log).
`Component.RAW: RAW DATA IN <iq xmlns='jabber:client' type='get' to='icq.gateway' id='aac5a' from='user.name@jabber.domain.suffix/Resource'>
<query xmlns='jabber:iq:register'></query>
</iq>
2018-01-07 02:08:41,431 INFO  Component.RAW: RAW DATA OUT <iq from="icq.gateway" id="aac5a" to="user.name@jabber.domain.suffix/Resource" type="error"><error type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
`

Using libpurple as the backend, it does not matter what protocol I use, the error is the same.
Using Debian Stretch with the precompiled binaries from your repository.

**Comment by vitalyster** [comment]
is database support enabled?

**Comment by Knezzen** [comment]
Don't try to configure stuff when you're tired. Yes, that was it vitalyster.
Thank you.

**Comment by vitalyster** [comment]
Note, it should work without database in server mode
