### ISSUE TITLE
unable to register with purple-hangouts

### ISSUE THREAD

**Issue by evgenyh** [SpectrumIM/spectrum2#258]
getting "Bad Request" as response message

> 28036: 2018-01-07 16:28:45,933 INFO  backend: accepting SSL certificate
28036: 2018-01-07 16:28:45,933 INFO  libpurple: certificate/x509/tls_cached:User ACCEPTED cert
Caching first in chain for future use as www.googleapis.com...
28036: 2018-01-07 16:28:45,935 INFO  libpurple: nss:Trusting CN=*.googleapis.com,O=Google Inc,L=Mountain View,ST=California,C=US
28036: 2018-01-07 16:28:45,935 INFO  libpurple: certificate:Successfully verified certificate for www.googleapis.com
28036: 2018-01-07 16:28:46,024 INFO  libpurple: http:Request 0x1381230 performed without success.
28036: 2018-01-07 16:28:46,024 INFO  libpurple: connection:Connection error on 0x13a6170 (reason: 0 description: Bad Request)
28036: 2018-01-07 16:28:46,024 ERROR backend: g_log purple_notify_close_with_handle: assertion 'handle != NULL' failed
28036: 2018-01-07 16:28:46,024 ERROR backend: g_log purple_request_close_with_handle: assertion 'handle != NULL' failed

**Comment by vitalyster** [comment]
It's a purple-hangouts issue, I see you already opened ticket there :)
