### ISSUE TITLE
Smetimes only every other message goes through.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#260]
Sometimes when sending messages, only every other message I send goes through Spectrum 2 and reaches its intended recipient. Is this a known or configuration problem.

**Comment by vitalyster** [comment]
This is not a valid issue report, please share backend you are using and versions of all depended software

**Comment by Zombie-Ryushu** [comment]
I am using purple-skypweb 1.4
spectrum2 2.0.5
ejabberd 2.1.13

**Comment by vitalyster** [comment]
check spectrum2.log and backend.log for any unusual error messages when you are lost some message, it looks like skypeweb issue and not spectrum

**Comment by Zombie-Ryushu** [comment]
I do not get this issue on Pidgin, and I have had this issue with AIM, back when it was functional.

**Comment by vitalyster** [comment]
I can't help without logs or steps to reproduce the error

**Comment by Zombie-Ryushu** [comment]
Thats what I am trying to get for you right now.
Here are my steps.

1. Using Pidgin, and an active Skype account, Connect one Pidgin account to Regular Skype, the other to the Spectrum 2 connected  XMPP Account that is running Spectrum2 in Gateway Mode. Register the Skype Purple Agent to the same account as you would connect to regular Pidgin with.

2. Enter a message to the XMPP account to the intended recipient on the Account in XMPP mode. Also have Regular Skype up in another tab as you do this.

3. If the message was successful, you will see the exact message you typed in the XMPP tab written in your regular Skype Tab. The other person will always see that message too.

 in Spectrum.log: You will see a Component.RAW Data in message with the name of the XMPP account, Component.RAW: 
RAW DATA IN <message from='account@pukey/Pidgin' to='skype_friend@skype.olympia.pukey' type='chat' id='purple4d192cf6'><composing xmlns='http://jabber.org/protocol/chatstates'/></message>

And then another similar one saying active xmlns with a similar message.

Not acll messages have an a composing xmlns. sometimes there is an active xmlns without a composing xmlns. This seems to be the instances where messages are not forwarded.

**Comment by vitalyster** [comment]
"composing" and "active" are xmpp chat states generated by Pidgin, it should be translated to "User is typing..." and "Message is read" notifications (or checkmarks, or any other common UI elements for these kind of events) on the recipient side, these are not plain messages. Still not clear to me what exactly is "not forwarded"

**Comment by Zombie-Ryushu** [comment]
Is there any possibility that messages intended for one service could be sent inadvertantly to some  other service? (a message for Skype being sent as a Discord Message? Perhaps based on the Port configuration of ejabberd)?

**Comment by vitalyster** [comment]
It is possible if you have incorrect setup of multiple "hosts" in ejabberd config, see https://github.com/SpectrumIM/spectrum2/issues/178

**Comment by Zombie-Ryushu** [comment]
Skype is now working consistently with Spectrum 2. It appears. I have yet to use other registered services.

**Comment by Zombie-Ryushu** [comment]
Issue turned out to be config in nature.
