### ISSUE TITLE
libpurple: sync account preferences

### ISSUE THREAD

**Issue by himselfv** [SpectrumIM/spectrum2#264]
Hi! I'm trying to solve the problem of not getting offline messages from purple-skypeweb (it receives them fine in Pidgin).

I've learned it properly requests conversations history "since last received message". It stores this timestamp in purple account settings:
```
void
skype_web_get_offline_history(SkypeWebAccount *sa)
{
	skypeweb_get_all_conversations_since(sa, purple_account_get_int(sa->account, "last_message_timestamp", ((gint) time(NULL))));
}
```
If it's missing, purple-skypeweb uses the current time => gets no history. So far so good.

It updates this timestamp when parsing messages. After I receive a few messages and then shut down spectrum2, I can verify that in the ```/var/lib/spectrum2/skype.transport``` directory there's ```accounts.xml``` which contains among other things a proper ```last_message_timestamp```.

So if I send something while the transport is offline, and the just start the transport again, the ```accounts.xml``` should be read, and purple-skypeweb should use the correct ```last_message_timestamp``` now.

But this doesn't happen. When I start the transport, ```accounts.xml``` vanishes and after a while is recreated with what I assume is blank content.

I've found this in libpurple backend's ```main.cpp :: initPurple()```:
```
remove("./accounts.xml");
```

So my question is, why is it being removed? Should it be? And if it should, what's the correct way to deal with this case? (And similar cases where plugins store stuff in purple's account settings).

**Comment by vitalyster** [comment]
IIRC, it was made for "server mode" without database, when user doesn't want to save any settings. Yes, it should not be deleted otherwise.

**Comment by vitalyster** [comment]
I have spent some time to understand the issue, and it requires too much work: currently spectrum recreated accounts.xml from database everytime it started. I have hardcoded last_message_timestamp sync with database, but skypeweb save it also for every conversation, we need to enumerate all settings before restore and it require core changes in spectrum storage backend

**Comment by himselfv** [comment]
Okay... What if I just keep the accounts.xml? (It doesn't seem to be recreated if it's present) Would anything break? Wouldn't DB and the file stay in sync automatically?

**Comment by vitalyster** [comment]
I don't think there will be problems in single user scenario, but can't say what can be break with multiple users

**Comment by himselfv** [comment]
Okay, thanks!

**Comment by Programie** [comment]
Removing and recreating the accounts.xml on every transport restart also results in the steam-mobile plugin losing it's access token and asking for the Steam Guard code every time.

**Comment by vitalyster** [comment]
The latest master does not delete accounts.xml. Need more testing in a multi-account environment
