### ISSUE TITLE
Feature: Support carbons of own messages done in other legacy network clients

### ISSUE THREAD

**Issue by himselfv** [SpectrumIM/spectrum2#265]
When I send a message from XMPP via spectrum2 -> purple-skypeweb, all other Skype instances receive a carbon copy of my own message.

Similarly, when I use purple-skypeweb via Pidgin, it too receives copies of my own messages made in other Skype instances.

But when used via spectrum2, it doesn't. It would be nice to have because otherwise only half of the conversation gets delivered.

Here's what purple-skypeweb does when handling such messages (it handles them fine, as a special case):
```
msg = purple_message_new_outgoing(convbuddyname, html, PURPLE_MESSAGE_SEND);
purple_message_set_time(msg, composetimestamp);
purple_conversation_write_message(conv, msg);
purple_message_destroy(msg);
```

libpurple has 3 callbacks for message delivery, ```conv_write_im```, ```conv_write_chat``` and a generic ```conv_write```. The docs say one of the two specific ones will be called, and only if its missing, the generic one.

Spectrum2-libpurple-backend implements all of them, but only the first two point to actual message handling. ```conv_write()``` implementation only contains a special case handling for purple-telegram.

If I'm not mistaken, libpurple doesn't seem to call ```conv_write_im``` for own messages. It goes straight to ```conv_write```. So that's the first part of the problem.

I (cautiously) propose adding an else clause to ```conv_write```, passing everything except the special purple-telegram case to ```conv_write_im()``` for standard handling:

```
else {
  //Handle all non-special cases by just passing them to conv_write_im
  conv_write_im(conv, who, msg, flags, mtime);
}
```

Next, in ```conv_write_im()``` spectrum2 has this check:
```
// Don't forwards our own messages.
if (purple_conversation_get_type_wrapped(conv) == PURPLE_CONV_TYPE_IM && (flags & PURPLE_MESSAGE_SEND || flags & PURPLE_MESSAGE_SYSTEM)) {
    return;
}
```

This filters out messages sent by the transport itself, but also carbon copies of our own messages which got delivered to us from elsewhere.

To avoid this, ideally we ought to remember sent messages and check against that list to see if the message is "ours". Unfortunately messages are sent via ```purple_conv_im_send()``` which neither accepts nor returns any kind of "message object" which we could remember. It only accepts a string, and checking by a string match is not reliable (what if there are two similar messages).

So I propose this ugly hack :)

1. Add a PURPLE_MESSAGE_* constant with unused value:
```
typedef enum {
    PURPLE_MESSAGE_SPECTRUM2_ORIGINATED = 0x80000000, //unused by libpurple
} PurpleMessageSpectrum2Flags
```

2. Instead of ```purple_conv_im_send``` use ```purple_conv_im_send_with_flags``` and pass this flag.

3.  In ```conv_write_im()``` check for this flag instead of simple ```PURPLE_MESSAGE_SEND```.

Here's a diff of proposed changes, which makes carbons of own messages work at my machine:

[f8d9a4.diff.txt](https://github.com/SpectrumIM/spectrum2/files/1651991/f8d9a4.diff.txt)

**Comment by vitalyster** [comment]
Didn't see how it turns into carbon message. How it looks on XMPP side? I think for proper carbon implementation we need to add flags into spectrum protobuf protocol

**Comment by himselfv** [comment]
Oh, wait, it gets delivered but gets attributed to the wrong person (to the recipient, not the sender). So it looks like a message to me, not from me.

And yeah, it doesn't seem ```handleMessage()``` can deal with this.

**Comment by vitalyster** [comment]
Yes, so we need: 

1. Define "carbon" flag in [ConversationMessage](https://github.com/SpectrumIM/spectrum2/blob/master/include/transport/protocol.proto#L70)
2. Push carbon messages from backend side
3. Wrap it on XMPP frontend side into XMPP Carbon payload and push to user

**Comment by himselfv** [comment]
Okay, I'm trying this now. By the way, there was another ignore case in ```conv_write_im()``` for ```PURPLE_MESSAGE_SYSTEM```:

```
if (purple_conersation_get_type_wrapped(conv) == PURPLE_CONV_TYPE_IM && (flags & PURPLE_MESSAGE_SYSTEM)) {
    return;
}
```

Just curious, is it needed? Why shouldn't system messages be forwarded?

**Comment by vitalyster** [comment]
Are there some interesting messages? If yes, then it should be forwarded with some another flag and pushed to user from special service jid (which sending 2FA requests, for example)

**Comment by himselfv** [comment]
Here's a rough implementation 
  https://github.com/himselfv/spectrum2/commit/c94670808dc1804c7cc59f7ae85d28cc5031e275

1. [Specs](https://xmpp.org/extensions/xep-0280.html#outbound) say the wrapper message must be ```from``` the local user's bare jid. XEP-0114 says transports can't send from outside their domain. The check can be disabled in ejabberd with ```check_from: false```, but this is a hack.

   ( I've tried sending carbons from the transport ID instead, but specs say such messages must be ignored and ignored they are.)

2. I had assumed ejabberd would just pass the carbons, but it creates carbons of carbons :D Our carbons are <sent><forward><message from=me to=them>, it wraps all of this in <received> and sends to every carbon subscriber. They just ignore it.

  As a workaround I'm adding a <no-copy /> hint. I'll ask ejabberd people about this later.

3. Carbons are not stored in [message archive (MAM)](https://xmpp.org/extensions/xep-0313.html) (at least on ejabberd). This makes sense normally because the original message have already been stored, but here we don't have one. I'm not sure what to do with this one.

Ideologically I think maybe they should be stored by the server after all. There's one line in XEP-0313 which says "all carbons should result in no more than one MAM entry", which suggests carbon-to-history handling is normal. I'll ask ejabberd guys, but they're but one client so any input is appreciated.

**Comment by vitalyster** [comment]
1. https://xmpp.org/extensions/xep-0356.html - privileged entity is able to send messages on behalf of the server

**Comment by himselfv** [comment]
Oh, indeed. Thanks! https://github.com/himselfv/spectrum2/commit/8131fcc165091dcdc0238b839c451c4ffdb9e606

I can even force carbons to be stored in the history now (with <store> hint), but as carbons, not as underlying messages.

**Comment by vitalyster** [comment]
Please do not use inlined xml, you can create new Swiften payloads/serializers in `include/Swiften` directory

**Comment by himselfv** [comment]
Alright, https://github.com/himselfv/spectrum2/commit/514cc50d1fd4481c12fb500033ccd8cbbb2cb935 (+ older commits).

Complex payload serializers such as <forwarded> or this <privilege> need access to ```payloadsCollection``` from ```Swift::Server``` or ```Swift::Component``` to produce serializers for child elements. It's protected and the way it's done now in XMPPFrontend.cpp, I had to do weird things to access it. If that won't do then how to go about it?

**Comment by vitalyster** [comment]
missing `GenericPayloadSerializer2.h` ?

**Comment by himselfv** [comment]
https://github.com/himselfv/spectrum2/commit/b5443130637800f581e551caa2e4de79b20b2f3e

**Comment by vitalyster** [comment]
> weird things to access it

Interesting.
Maybe it will be better to subclass `FullPayloadParserFactoryCollection` ?

**Comment by himselfv** [comment]
But ```Swift::Server``` and ```Swift::Component``` don't have the methods to set the new versions, don't they?

I suspect that the clean way to do it is to subclass ```Swift::Server``` and ```Swift::Component``` and add any factories there. But it's your code, I'm okay with it either way.

**Comment by vitalyster** [comment]
I see they set parserFactories in the constructor. But I'm ok with your solution too

**Comment by himselfv** [comment]
Soo what do we do? Do I pull request this or should I subclass Server/Component or what?)

**Comment by vitalyster** [comment]
Are there remaining issues?

**Comment by vitalyster** [comment]
We also need to check should we bump required Swiften version (to access Carbons support)

**Comment by himselfv** [comment]
Not so far as spectrum2 is concerned, I think:

1. I've contacted ejabberd guys about producing carbons of carbons and they've said that's fine and to continue using ```<no-copy>```.

2. mod_mam still doesn't archive carbons but that's a different story.

I'm not sure how to check which version is required, but ```CarbonsSent.h``` has been present [since 2015](https://github.com/swift/swift/commits/master/Swiften/Elements/CarbonsSent.cpp) so maybe it's already covered.

**Comment by vitalyster** [comment]
Swift 2.0 was released much earlier - http://swift.im/git/swift/log/?h=swift-2.x
Please create PR to check all issues on Travis

**Comment by vitalyster** [comment]
i think we can conditionally enable carbons support when SWIFTEN_VERSION is greater than 3, or something else

**Comment by himselfv** [comment]
Something like this? https://github.com/SpectrumIM/spectrum2/pull/267  (```SWIFTEN_SUPPORTS_CARBONS```)

**Comment by vitalyster** [comment]
Exactly!

**Comment by thundergreen** [comment]
Didn't know that spectrum is still under development ;) nice and waiting the changes .carbon is nice

**Comment by vitalyster** [comment]
Just tested this with prosody and skypeweb: everything worked except message didn't showed in chat :) I think forwarded message missing resource part in `from` attribute, which should match `to` attribute in carbon wrapper

**Comment by himselfv** [comment]
How did it look like, in XML? It should look like this:
```
<message from="transport.com" to="server.com"> <!-- XEP-0356 wrapper -->
<privilege><forwarded>
<message from="account@server.com" to="account@server.com/resource" > <!-- XEP-0280 wrapper -->
<sent><forwarded>
<message from="account@server.com" to="contact@transport.com"> <!-- original message -->
```
Are you talking about the ```from``` attribute in the ```original message```?

**Comment by vitalyster** [comment]
I’m talking about carbon message from server to client: it have correct `to` (with resource), but wrapped forwarded message have my bare jid in `from`

**Comment by himselfv** [comment]
It should probably have ```/bot``` resource then? (Similar to how all other transport contacts have it)

**Comment by vitalyster** [comment]
Please add /bot and I will try

**Comment by himselfv** [comment]
Here https://github.com/SpectrumIM/spectrum2/pull/268

**Comment by vitalyster** [comment]
Awesome, thanks! Works for me now, at least for "send" messages

**Comment by vitalyster** [comment]
BTW, it will be good to check if we are not privileged and/or carbons not supported on the server to log about it
