### ISSUE TITLE
Packages are built in debug mode, with optimisations disabled

### ISSUE THREAD

**Issue by sicherha** [SpectrumIM/spectrum2#270]
Both the Debian and RPM packages are configured with `-DCMAKE_BUILD_TYPE=Debug`, causing compiler optimisations to be disabled completely (`-O0`). Is this intentional? I would assume that packages should normally be built with `-DCMAKE_BUILD_TYPE=Release`.

**Comment by vitalyster** [comment]
As far as I understand, packages should be built in RelWithDebInfo mode, because they should have debuginfo packages.
