### ISSUE TITLE
hangouts groups support with purple-hangouts 0.54 & 0.56

### ISSUE THREAD

**Issue by evgenyh** [SpectrumIM/spectrum2#278]
Using this backend all works fine escept groups.
when someone adding me to group , spectrum2 not being notified on this at all, so no new entry in roster is being created.
And then when someone sending messages to such group I can only see entries in log like this : 
NetworkPluginServer: handleConvMessagePayload: No conversation with name UgyOoS6njI6J-EnJN9p4AaABAQ

* tested with purple-hangouts 0.54 & 0.56

thanks

**Comment by vitalyster** [comment]
requires #68 to be implemented

**Comment by diggit** [comment]
@evgenyh group chats from purple-hanouts does not work entirely or suport is just limited?
I have prosody server with spectrum2 and purple-hangouts and I am struggling to set up hangouts group chat support.
Sorry for necrobumping.
