### ISSUE TITLE
Spectrum's XMPP messages don't set active chatstate

### ISSUE THREAD

**Issue by dos1** [SpectrumIM/spectrum2#282]
XEP-0085 specifies that when supporting chat states, every message should include `<active xmlns='http://jabber.org/protocol/chatstates'/>` tag. However, Spectrum (at least when using purple and purple-facebook as a backend and XMPP transport as a frontend) does send two separate messages: first one with `<active>` tag only, and second one with body and no chatstate.

This breaks some clients' chatstate handling, like Psi, which then stops to send its own chatstates, which in turn results in Facebook messages never marked as read until replied.

**Comment by dos1** [comment]
Somewhat related to #136

**Comment by vitalyster** [comment]
Isn't it Psi should send active chatstate and then Spectrum should send read event to libpurple?

**Comment by dos1** [comment]
It is and it does, however, when Spectrum violates XEP-0085, Psi stops sending them anymore.

It's easy to check, as Psi sends chatstates to Facebook contact on Spectrum only between when they start typing (setting some chatstate) and when they send message (resetting chatstate to null).
