### ISSUE TITLE
Case-insensitive comparison of VCard parameters

### ISSUE THREAD

**Issue by ValdikSS** [SpectrumIM/spectrum2#289]
Non-standard VCard fields should be compared in a case-insensitive way
https://github.com/SpectrumIM/spectrum2/blob/master/backends/libpurple/main.cpp#L1540

Telegram libpurple backend uses "First name" and "Last name" (with lowercase n) and "Display Name" (with capital N).

**Comment by vitalyster** [comment]
libpurple does not have standard types and/or names for vcard fields and all plugins uses different names for that. I will accept patch for case-insensitive comparison, but it will not a complete solution
