### ISSUE TITLE
[Dockerfile] please add purple-hangouts

### ISSUE THREAD

**Issue by elfrinjo** [SpectrumIM/spectrum2#293]
Please add purple-hangouts to the Dockerfile.
As it is part of Fedora, it can bee added to the `dnf install` command (Tested/Works4me).

**Comment by vitalyster** [comment]
Just add required commands [there](https://github.com/SpectrumIM/spectrum2/blob/master/Dockerfile#L9) and send pull request :)

**Comment by elfrinjo** [comment]
sure, here we go: #294 :)

**Comment by vitalyster** [comment]
Thanks, spectrum:latest image should be updated automatically in a few minutes
