### ISSUE TITLE
Cannot properly use prpl-steam-mobile with spectrum2 because of "steam guard"

### ISSUE THREAD

**Issue by truenicoco** [SpectrumIM/spectrum2#301]
Steam has a feature called [Steam Guard](https://support.steampowered.com/kb_article.php?ref=4020-ALZM-5519). Each time you log in through a new device, a "steam guard code" is sent to your email and you need to enter it to successfully authenticate.

This step is implemented in the [prpl-steam-mobile backend](https://github.com/EionRobb/pidgin-opensteamworks/) and is handled correctly when using Finch (and I guess when using Pidgin too). It pops up a dialog box prompting for the *steam guard code* the first time you log in.

Unfortunately this does not seem to be implemented in spectrum2:

`WARN  backend: Unhandled request input. primary=Set your Steam Guard Code`

This results in being unable to subscribe properly to the transport, despite a success message on the client side (at least in gajim). The transport then appears as an offline buddy of the "transports" category in the roster tab, which somehow indicates that something is wrong.

A workaround is to disable steam guard, but this isn't optimal as steam disables some features when you do so.

**Comment by vitalyster** [comment]
Spectrum version?

**Comment by truenicoco** [comment]
```
$ apt-cache policy spectrum2
spectrum2:
  Installed: 1:2.0.7-1
  Candidate: 1:2.0.7-1
  Version table:
 *** 1:2.0.7-1 500
        500 http://packages.spectrum.im/spectrum2 stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```
