### ISSUE TITLE
Run spectrum2 as non-root user in docker image

### ISSUE THREAD

**Issue by languitar** [SpectrumIM/spectrum2#303]
Would be nice of the dockerfile contained a USER definition to avoid running the daemon with root permissions. Unfortunately, simply adding a `--user` when starting the container doesn't work because of permissions errors.

**Comment by vitalyster** [comment]
transport accepts `user` and `group` in `[service]` config section

**Comment by languitar** [comment]
alright, but is there a user available in the docker image that is suitable?

**Comment by vitalyster** [comment]
spectrum manager reads config files as root and starts services as specified user, any standard user should be suitable

**Comment by languitar** [comment]
Ah, there is even a `spectrum` user in the image.
