### ISSUE TITLE
Necessary dependencies

### ISSUE THREAD

**Issue by sdfg2** [SpectrumIM/spectrum2#311]
What are the absolute minimum necessary dependencies, and what do they provide?

For example, if I'm using spectrum to provide gateways to Telegram, Steam (using libpurple) etc for an XMPP account, do I need swiften?  Or is swiften what spectrum uses to talk to my XMPP server?

I'm trying to minimize deps because some of the backends are fairly unforgiving when it comes to requirements.  libcommuni drags in qt and everything up to mesa and libgl, and there are other bits and pieces kicking around that drag in things like alsa-libs and gstreamer.  Doesn't make sense on a headless server :-)

**Comment by vitalyster** [comment]
Yes, swifter is the core dependency to talk with XMPP server.
You can disable unneeded backends, like `cmake . -DENABLE_IRC=OFF` will disable communi backend. Check CMakeLists.txt for other `ENABLE_*` options
