### ISSUE TITLE
Telegram videos received as links to server filesystem

### ISSUE THREAD

**Issue by mbirth** [SpectrumIM/spectrum2#313]
This might be related to #161. Web storage is configured for the Telegram backend. However, video files seem to be downloaded by purple-telegram already and Spectrum2 only receives a message with the link to that local file:

    7396: 2018-11-28 22:17:56,382 INFO  backend: Received message body='[video download_5474206302907400872 <file:////var/lib/spectrum2/telegram.myserver.com/telegram-purple/+4915112345678/downloads/download_5474206302907400872> video/ 4.1 MB]' xhtml='[video <a href="file:////var/lib/spectrum2/telegram.myserver.com/telegram-purple/+4915112345678/downloads/download_5474206302907400872">download_5474206302907400872</a> video/ 4.1 MB]' name='My Contact'

In this case, this was an MP4 file. However, since the link points to the local file on the Spectrum server, I couldn't watch the video in clients.

This might also be related to majn/telegram-purple#414 although I'm using the fork EionRobb/telegram-purple .

**Comment by vitalyster** [comment]
https://github.com/SpectrumIM/spectrum2/pull/255 duplicate
