### ISSUE TITLE
Please Document Image Transfer

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#333]
Please Document Image Transfer. Try and clearly explain on both the Prosody side, and on the Spectrum2 Side, how to setup image encoding using Apache.

**Comment by vitalyster** [comment]
[Web storage](https://spectrum.im/documentation/configuration/web_storage.html) documentation is here. No need anything expect these two options.
You problem not is in spectrum configuration but in libpurple protocol plugin, I did not respond for problems in libpurple plugins
