### ISSUE TITLE
Mixed up roster names

### ISSUE THREAD

**Issue by synchrone** [SpectrumIM/spectrum2#334]
I've set up libpurple-telegram plugin, and some of my contacts' display names that use national characters are mixed up on roster import, with vCard reporting their actual (correct) JID.

I also see their broken utf-8 names in vCard stanzas in logs. I've tried [purple] encoding=utf-8 and windows-1251 with no effect either.
```
INFO  Component.RAW: RAW DATA OUT <iq from="telegram.domain.tld" id="f527fc17-63c9-4324-a57c-79b737727fee" to="syn@domain.tld/gajim.Z1DBUB65" type="set"><x xmlns="http://jabber.org/protocol/rosterx">
<item action="add" jid="??????????\20????????????\20#1@telegram.domain.tld" name="?????????????????? ?????????????????????? #1">
```
as seen here, counting the question marks, the JID does not match the display name.

Sending a message to national-character-using JID also sends it to some other contact, and their responses are coming back from another JID.

**Comment by vitalyster** [comment]
Telegram protocol plugin is broken by design - https://github.com/SpectrumIM/spectrum2/issues/175
