### ISSUE TITLE
how to add 3rd party libpurple plugins

### ISSUE THREAD

**Issue by evgenyh** [SpectrumIM/spectrum2#335]
I successfully compiled 3rd party plugin from source and dropped it into /usr/lib64/purple-2 where the rest of officially supported plugins resides.

the question is how do I refer to in cfg file ? 
I assume I should refer to it via protocol=prpl-somename way. what how to know what protocol name should be used ?

thanks

**Comment by vitalyster** [comment]
Each libpurple plugin have [PurplePluginInfo](https://github.com/EionRobb/purple-discord/blob/master/libdiscord.c#L5530) inside and [its 9th field](https://github.com/EionRobb/purple-discord/blob/master/libdiscord.c#L5541) is plugin ID, which in this case turned into [this prpl-* constant](https://github.com/EionRobb/purple-discord/blob/master/libdiscord.c#L53)
