### ISSUE TITLE
HTTP Upload / Out-of-band data for native rendering of images in XMPP clients

### ISSUE THREAD

**Issue by stv0g** [SpectrumIM/spectrum2#345]
I am currently trying to render received images from my transport natively within my XMPP client without requiring the user to click on a link which points to Spectrums `web_url`.

I am wondering what the currently recommended solution is?

Can we send HTML formatted messages including `<img>` tags?
Or should we use [Out-of-band Data](https://xmpp.org/extensions/xep-0066.html) (XEP-66)

Should be handled by Spectrum or the backends themselves?

**Comment by Natureshadow** [comment]
XHTML-IM is not implemented anymore by current clients it seems, so oob is the way to go. But if you just hand that part of to HTTP Upload, the HTTP Upload service will do the right thing for you.

**Comment by vitalyster** [comment]
Links can be sent now using attachment field of the ConversationMessage protobuf structure, they will be mapped to OOB payload of XMPP frontend
