### ISSUE TITLE
ICQ: Received unexpected response from https://api.icq.net/aim/startOSCARSession 

### ISSUE THREAD

**Issue by NoServiceRu** [SpectrumIM/spectrum2#346]
Hello!
ICQ changes own protocol from OSCAR to WIM. And now transport doesn't work... 
Reponse from ICQ:
"Received unexpected response from https://api.icq.net/aim/startOSCARSession"

Library libicyque.so copy to folder /usr/lib/purple-2/
Libraries spectrum2 was updated from repository.

**Comment by vitalyster** [comment]
You need to change `protocol` from `prpl-icq` to `prpl-eionrobb-icyque`
