### ISSUE TITLE
After update to 2.0.11, libpurple_backend segfaults

### ISSUE THREAD

**Issue by mbirth** [SpectrumIM/spectrum2#354]
Yesterday, I've let LaunchPad create packages for the new release here: https://launchpad.net/~mbirth/+archive/ubuntu/ppa . I previously had 2.0.10 created in the same way and those worked just great.

However, after updating to the 2.0.11 packages on my Raspberry Pi 3 (arm64), Hangouts (purple-hangouts) and Facebook (purple-facebook) gave errors "Internal server error, please reconnect." every 5-10 minutes.

`spectrum2.log` shows "Starting new backend..." in these intervals.

`backend.log` just stops after startup with no apparent error message and then starts with the log from the new instance (different PID):

```
1980: 2019-07-13 12:05:22,944 INFO  libpurple: nss/x509:Exporting certificate to /var/lib/spectrum2/hangouts.myserver.com/certificates/x509/tls_peers/clients6.google.com
1980: 2019-07-13 12:05:22,944 INFO  libpurple: util:Writing file /var/lib/spectrum2/hangouts.myserver.com/certificates/x509/tls_peers/clients6.google.com
1980: 2019-07-13 12:05:22,966 INFO  libpurple: nss:Trusting CN=*.google.com,O=Google LLC,L=Mountain View,ST=California,C=US
1980: 2019-07-13 12:05:22,966 INFO  libpurple: certificate:Successfully verified certificate for clients6.google.com
1983: 2019-07-13 12:05:23,240 INFO  SQLite3Backend: Opening database /var/lib/spectrum2/hangouts.myserver.com/database.sql
1983: 2019-07-13 12:05:23,243 INFO  backend: Setting libpurple plugins directory to: ./plugins
1983: 2019-07-13 12:05:23,243 INFO  backend: Setting libpurple cacerts directory to: ./ca-certs
1983: 2019-07-13 12:05:23,243 INFO  backend: Setting libpurple user directory to: /var/lib/spectrum2/hangouts.myserver.com
1983: 2019-07-13 12:05:23,243 INFO  backend: Will use glib based event loop
```

Trying to start the backend manually gives a Segmentation fault:

```
$ sudo -u spectrum /usr/bin/spectrum2_libpurple_backend --host 127.0.0.1 --port 32875 --service.backend_id=1 -j hangouts.myserver.com /etc/spectrum2/transports/hangouts.cfg
Segmentation fault
```

After downgrading to 2.0.10, everything works again.

**Comment by vitalyster** [comment]
https://spectrum.im/documentation/management/getting_backtrace.html ?

**Comment by vitalyster** [comment]
OK, I'm reproduced the issue, @himselfv can it be in your changes?

**Comment by vitalyster** [comment]
git bisect says:
> f1f0c97a262b55177c8f0288c533fe3ebee975d9 is the first bad commit

**Comment by vitalyster** [comment]
I did revert these commits and published 2.0.12

**Comment by mbirth** [comment]
Thanks a lot! I will upload the new version to LaunchPad later today. :)

**Comment by vitalyster** [comment]
We can promote your PPA on spectrum site if you want :) But lets discuss in another issue

**Comment by mbirth** [comment]
2.0.12 seems to work fine! Many thanks! (Also, please don't promote the PPA. It only carries packages for Ubuntu disco and I don't always get to update it in a timely manner.)

**Comment by himselfv** [comment]
Anyone has more details on how to reproduce? Maybe a config? Trying with Ubuntu 16.04 in server_mode=1 with latest purple-hangouts, the backend starts normally (without accounts, anyway).

@mbirth 
> backend.log just stops after startup with no apparent error message
I.e. right after startup, with no usable time at all?

**Comment by vitalyster** [comment]
@himselfv crashed right after login somewhere in glib, I was not able to find spectrum lines in backtrace

**Comment by himselfv** [comment]
@mbirth: Can you please provide some more details on how you run it? Like the contents of that hangouts.cfg, the output of "cmake ."? I tried that commit on two versions of CentOS and one Ubuntu, can't crash it.

**Comment by mbirth** [comment]
Build log should be https://launchpadlibrarian.net/432859840/buildlog_ubuntu-disco-arm64.spectrum2_2.0.11-1_BUILDING.txt.gz . This was on a Raspberry Pi 3 with Ubuntu Server arm64.

My `hangouts.cfg`:

```ini
[service]
frontend=xmpp
user=spectrum
group=spectrum
jid = hangouts.myserver.com
password = ******
server = localhost
port = 8888
backend_host = 127.0.0.1
users_per_backend=10
backend=/usr/bin/spectrum2_libpurple_backend
protocol=prpl-hangouts
web_directory=/var/www/html/chat/uploads
web_url=https://xmpp.myserver.com/uploads
oob_split=false

[identity]
name=Spectrum Hangouts Transport
type=xmpp
category=gateway

[logging]
config = /etc/spectrum2/logging.cfg
backend_config = /etc/spectrum2/backend-logging.cfg

[database]
type = sqlite3

[registration]
enable_public_registration=1
username_label=Google username:
instructions=Enter your Google account, leave password empty.
```

(I think `oob_split=false` was added later, but the rest was like that before.)
