### ISSUE TITLE
Компиляция spectrum2 завершается ошибкой

### ISSUE THREAD

**Issue by opiums9** [SpectrumIM/spectrum2#360]
После того как мои ICQ и Facebook транспорты перестали работать я решил обновить spectrum2 до более новой версии, но наткнулся на ошибку во время компиляции, что может быть не так?
Лог действий: [https://gist.github.com/opiums9/4a080bb04ec032bc3440885c2b45d058](https://gist.github.com/opiums9/4a080bb04ec032bc3440885c2b45d058)

**Comment by vitalyster** [comment]
Ubuntu version?
jsoncpp version?

**Comment by opiums9** [comment]
Operating System: Raspbian GNU/Linux 8 (jessie)
Kernel: Linux 4.9.35-v7+
Architecture: arm
gcc version 4.9.2 (Raspbian 4.9.2-10+deb8u1)
А где посмотреть именно для jsoncpp?

**Comment by vitalyster** [comment]
`apt cache show libjsoncpp-dev`
https://packages.debian.org/jessie/libjsoncpp-dev
0.6.0 is too old

**Comment by opiums9** [comment]
Package: libjsoncpp-dev
Source: libjsoncpp
Version: 0.6.0~rc2-3.1
Architecture: armhf

Стоит обновляться до Stretch?

**Comment by vitalyster** [comment]
Стоит обновляться до buster :)
