### ISSUE TITLE
Would like the ability to host Spectrum2 Web Registration on Apache.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#362]
I Would like the ability to host Spectrum2 Web Registration on Apache. I need to be able have users able to manage their registrations and mapping. But I have an Apache server I'd like to use to host the web interface.

**Comment by vitalyster** [comment]
Just configure reverse proxy to spectrum2 web interface - https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by Zombie-Ryushu** [comment]
I thought of that, and there's a reason I can't do that.
