### ISSUE TITLE
Issue with pidgin-sipe on Spectrum2. Need the ability to remotely disable.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#363]
I work for an organization that uses Microsoft Lync, AKA Skype for Business. The problem is that when two clients connect, one official Lync Client, and one Pidgin, depending on a seeming coin toss of chance, all messages could wind up going to the Pidgin/Spectrum Client, rather than the official Lync Client.

I use Pidgin to utilize Skype for Business at home. If I leave home with Skype for Business/Lync Running, I miss any messages intended for my at work workstation. This is a problem with Lync itself, not Pidgin, or purple-sipe, or Spectrum 2.

The only way to stop this is to Secure Shell in, and kill the entire Pidgin instance via a Terminal on my Phone, which terminates my entire Pidgin session, and any networks I am connected too. in addition to my history.

I'd like the ability to enable and disable spectrum2 accounts with either the web interface, or a command to the XMPP bot.

**Comment by vitalyster** [comment]
Any XEP-0050 capable client can disable spectrum account, not a spectrum issue
