### ISSUE TITLE
A Normal non-sudo user cannot add an account to spectrum.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#364]
A Normal non-sudo user cannot add an account to spectrum. One of my users attempted to do so, and spectrum2_manager became unresponsive and hanged at the terminal.
I then did the same mapping with sudo and it worked.

**Comment by vitalyster** [comment]
spectrum2_manager is not an end-user command, again, user should add accounts via service discovery or web interface
