### ISSUE TITLE
Telegram messages with images

### ISSUE THREAD

**Issue by delister** [SpectrumIM/spectrum2#367]
I use libpurple backend for connect to telegram. When I send image (from conversation) to telegram contact, He get link to image. Image it's accessible by this link. So it  should be (link instead of image) ? Or am I setting something wrong ?

Server ejabberd with enabled http_upload module, max_size is 500 Mb. Sended image size is 200 Kb.

**Comment by vitalyster** [comment]
First rule with libpurple plugins - test it with pidgin(finch). If behavior is the same then it is plugin issue, not spectrum

**Comment by delister** [comment]
In pidgin image sending as file. Telegram user see thumbnail image and download button.

**Comment by vitalyster** [comment]
OK now I understand, spectrum does not re-upload received image to libpurple as "file", so yes it should be a link, until someone implemented proper file transfers

**Comment by delister** [comment]
Tnx, for the to be image display as image in telegram (not a file and not a link) need to implement it in telegram-purple ? or for this also need to implement file transfers in spectrum side ?

**Comment by vitalyster** [comment]
If pidgin works correctly with telegram-purple then nothing to do on their sides, only in spectrum

**Comment by heeplr** [comment]
i get this error when sending an image from conversations via telegram-purple. (It used to work before. Not sure since when it stopped working as I don't send a lot of images):
```
Mar  1 16:45:32 host spectrum2[5954]: 5954: 2021-03-01 16:45:32,721 INFO  Component.RAW: RAW DATA IN <iq type='set' to='foo@telegram.example.com/bot' from='bar@example.com/Conversations.IMtG' id='DykBqnBSlvwf'><jingle xmlns='urn:xmpp:jingle:1' action='session-initiate' sid='7APugYBBFX9plFbiyTnNUQ'><content creator='initiator' senders='initiator' name='NJU5ge9dRPHSQR9DPSAMpg'><description xmlns='urn:xmpp:jingle:apps:file-transfer:3'><offer><file><size>218996</size><name>fa0b64e0-1388-4b30-9197-154e85cc38bb.jpg</name></file></offer></description><transport block-size='8192' xmlns='urn:xmpp:jingle:transports:ibb:1' sid='26at+zU5chqyBIQanLXukQ'/></content></jingle></iq>
Mar  1 16:45:32 host spectrum2[5954]: 5954: 2021-03-01 16:45:32,722 INFO  Component.RAW: RAW DATA OUT <iq from="telegram.example.com" id="DykBqnBSlvwf" to="bar@example.com/Conversations.IMtG" type="error"><error type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
```

**Comment by vitalyster** [comment]
Spectrum never had jingle file-transfers support, and your client should detect this and should not try that
