### ISSUE TITLE
PostgreSQL support: compilation with libpqxx >= 7.x.x fails

### ISSUE THREAD

**Issue by ConiKost** [SpectrumIM/spectrum2#390]
If spectrum2 is compiled with postgresql support, it will fail, if libpqxx >= 7.x.x is used. If older 6.x.x is used, compilation will work.

Build log: https://pastebin.com/J32rNqaN

**Comment by vitalyster** [comment]
Fixed in current master

**Comment by ConiKost** [comment]
Yep, it works. Thanks!
