### ISSUE TITLE
Get Info does not accurately reflect the actual status of a user.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#394]
Get Info does not accurately reflect the actual status of a user to what it would be on a given, native plugin.
It only gives 

Resource: bot
Followed by the XMPP Image Avatar of the user. It also takes a very long time to recover. 

XMPP Info screens should reflect the same information as the native plugins.

**Comment by vitalyster** [comment]
Duplicate of #200
