### ISSUE TITLE
[purple-instagram] unable to introduce login code

### ISSUE THREAD

**Issue by Megver83** [SpectrumIM/spectrum2#397]
I'm currently trying to use instagram transport from hot-chilli.net, and when doing so I get a mail with a six digit numeric code that (in theory) I should introduce when logging in from the website. However, in Pidgin, purple-instagram let me introduce the code, but when using it with spectrum there's no way (or I haven't found one).

Idk if this is the normal behavior and I'm doing something wrong, or if it is a bug.

**Comment by vitalyster** [comment]
This is fixed in master, `latest` Docker image has this fix now
