### ISSUE TITLE
Can Spectrum 2 be used to "bridge" two or more Legacy networks?

### ISSUE THREAD

**Issue by Zombie-Ryushu** [SpectrumIM/spectrum2#399]
I have a question, can Spectrum 2 be used to create a "Bridge" between two Legacy networks, like Phoenix AIM, and Escargot MSN?

This needs to function such that Escargot Users can see Phoenix Users and Vice versa.

**Comment by vitalyster** [comment]
You can start as many spectrum instances as you want and add of them to your XMPP account.

**Comment by Zombie-Ryushu** [comment]
I want Phoenix users to be able to see Escargot Users ansd Vice versa without either user type using XMPP.
