### ISSUE TITLE
Twitter Backend Crashing

### ISSUE THREAD

**Issue by qstambaugh** [SpectrumIM/spectrum2#450]
## Versions

  - OS: Debian GNU/Linux 11 (bullseye) x86_64
  - Spectrum2 version: 2.1.3
  - Prosody version: 0.12.1

## Steps to reproduce the problem

  1. Register with Twitter backend
  2. Send `#timeline` message to it

## Expected behavior

Receive current Twitter timeline for account

## Actual behavior

Ends up crashing, giving no feedback to the user. It also doesn't add users to my roster when switched to mode 1. It also doesn't receive new tweets in the background. The only thing I can get it to do without crashing is send a tweet. I've attached a log of it crashing and my configuration

[twitter.txt](https://github.com/SpectrumIM/spectrum2/files/9035661/twitter.txt)
[spectrum2.log](https://github.com/SpectrumIM/spectrum2/files/9035662/spectrum2.log)

**Comment by vitalyster** [comment]
Most likely it is already fixed in https://github.com/SpectrumIM/spectrum2/commit/4893499f58f6085f12a07644c307dd8bc0381809
