### ISSUE TITLE
Invalid MUC presence does not allow some clients to use groupchats

### ISSUE THREAD

**Issue by vitalyster** [SpectrumIM/spectrum2#60]
When joining MUC from client we receive presences from participants and from MUC itself, but due to bug in swiften 2 we receive `<presence from='room@conference.domain.tld/' />` and some clients does not consider we complete room join and does not allow to send/receive messages.
Upgrade to swiften 3 #58  should solve this

**Comment by vitalyster** [comment]
I'm not able to reproduce it anymore, can you provide steps?

**Comment by ValdikSS** [comment]
Sorry, I was using Jessie package, which includes swiften 2. Switching to Stretch package fixed the issue.
