### ISSUE TITLE
Optionally list hidden rooms in service discovery (disco#items)

### ISSUE THREAD

**Issue by moyamo** [SpectrumIM/spectrum2#81]
[XEP-0045 (Multi-User-Chat)](http://xmpp.org/extensions/xep-0045.html#disco-rooms) says that the room discovery SHOULD return a full list of public rooms. Whatsapp only has hidden rooms. I suggest spectrum also optionally allow backends to make hidden rooms visible to specific users. The change to the room list will be like this

``` protobuf
message RoomList {
    repeated string room;
    repeated string name;
    repeated string user;
}
```

`user` can be a comma seperated list of usernames (or something more structured, if you wish). If `user` is blank then the room is public, otherwise it is only visible to the specified users.

**Comment by vitalyster** [comment]
If I understand issue correctly, nothing to do there, room discovery only show user rooms
