### ISSUE TITLE
Kick users from MUC when spectrum exits

### ISSUE THREAD

**Issue by moyamo** [SpectrumIM/spectrum2#90]
When spectrum exits it, rightfully, sets the presence of all buddies to offline. This is the correct behaviour because buddy will no longer receive messages from the user.

However, the user is not kicked from the MUCs he has joined. This is incorrect behaviour as the participants of the MUC will not receive messages from the user. The user should be kicked from all MUCs when spectrum exits.

**Comment by vitalyster** [comment]
Works for me with libpurple backend
> --- vt has been kicked by transport: Spectrum 2 transport is being shut down.

transwhat-specific issue?

**Comment by moyamo** [comment]
I'm not sure. I don't really remember since I discovered this bug a long time ago and am not using transwhat anymore.
